name: Docker

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: openefi_testing
  PAT: "no tengo que ser tarado y pushear mi pat"

jobs:
  # Run tests.

  test_firmware:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install deps
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sh get-docker.sh
          apt install -y nodejs npm
          npm i -g junit-viewer
         
      - name: Log into registry
        run: |
          echo "${PAT}" | docker login docker.pkg.github.com -u FDSoftware --password-stdin
          docker pull docker.pkg.github.com/openefi/openefi_testing/openefi_testing:latest

      - name: pull image & run script
        run: |
          docker images
          docker create --name openefi_testing_container docker.pkg.github.com/openefi/openefi_testing/openefi_testing
          docker cp ./firmware.bin openefi_testing_container:/mnt/firmware.bin
          docker container start openefi_testing_container
          docker container wait openefi_testing_container
          docker cp openefi_testing_container:/mnt/report.xml ./openefi_report.xml

      - name: create html ./openefi_report.xml
        run: |
          junit-viewer --results=./openefi_report.xml >> openefi_report.html